// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as React from "react";

var textOnPrimary = {
  NAME: "var",
  VAL: "--theme-text-on-primary"
};

var Theme = {
  textOnPrimary: textOnPrimary
};

var appContainer = CssJs.style([
      CssJs.width({
            NAME: "vw",
            VAL: 100
          }),
      CssJs.height({
            NAME: "vh",
            VAL: 100
          }),
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("center"),
      CssJs.flexDirection("column"),
      CssJs.color(textOnPrimary)
    ]);

var Styles = {
  appContainer: appContainer
};

function AppContainer$default(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: appContainer
            }, children);
}

var $$default = AppContainer$default;

export {
  Theme ,
  Styles ,
  $$default ,
  $$default as default,
  
}
/* appContainer Not a pure module */
