// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";

var btnReset = CssJs.style([
      CssJs.background("none"),
      CssJs.borderWidth(CssJs.px(0)),
      CssJs.cursor("pointer"),
      CssJs.unsafe("appearance", "none"),
      CssJs.unsafe("WebkitTapHighlightColor", "rgba(0, 0, 0, 0)")
    ]);

var hover = CssJs.style([CssJs.media("(hover: hover)", [CssJs.selector("&:hover", [CssJs.transform({
                        NAME: "scale",
                        VAL: [
                          1.08,
                          1.08
                        ]
                      })])])]);

export {
  btnReset ,
  hover ,
  
}
/* btnReset Not a pure module */
