// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as React from "react";

var cycleControls = CssJs.style([
      CssJs.boxSizing(CssJs.borderBox),
      CssJs.borderRadius(CssJs.px(8)),
      CssJs.width(CssJs.pct(100)),
      CssJs.height(CssJs.px(48)),
      CssJs.border(CssJs.px(1), CssJs.solid, CssJs.$$var("--theme-secondary")),
      CssJs.display("flex"),
      CssJs.alignItems(CssJs.center),
      CssJs.justifyContent(CssJs.spaceBetween),
      CssJs.zIndex(1),
      CssJs.overflow(CssJs.hidden)
    ]);

var Styles = {
  cycleControls: cycleControls
};

function CycleControls$default(Props) {
  var children = Props.children;
  return React.createElement("section", {
              className: cycleControls
            }, children);
}

var $$default = CycleControls$default;

export {
  Styles ,
  $$default ,
  $$default as default,
  
}
/* cycleControls Not a pure module */
