// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as React from "react";

var footer = CssJs.style([
      CssJs.fontSize(CssJs.rem(0.75)),
      CssJs.opacity(0.7),
      CssJs.textAlign("center"),
      CssJs.position("absolute"),
      CssJs.left("zero"),
      CssJs.right("zero"),
      CssJs.bottom(CssJs.px(20)),
      CssJs.media("max-height: 500px", [CssJs.display("none")]),
      CssJs.selector("a", [
            CssJs.color(CssJs.$$var("--theme-text-on-primary")),
            CssJs.textDecoration("none"),
            CssJs.hover([CssJs.textDecoration("underline")]),
            CssJs.active([CssJs.textDecoration("underline")]),
            CssJs.focus([CssJs.textDecoration("underline")])
          ])
    ]);

var Styles = {
  footer: footer
};

function Footer$default(Props) {
  return React.createElement("footer", {
              className: footer
            }, React.createElement("p", undefined, "A project by ", React.createElement("a", {
                      href: "https://traviskaufman.io",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Travis Kaufman")));
}

var $$default = Footer$default;

export {
  Styles ,
  $$default ,
  $$default as default,
  
}
/* footer Not a pure module */
