// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./assets/logo.svg";

var logo = LogoSvg;

function LogoImage$default(Props) {
  return React.createElement("img", {
              style: {
                marginBottom: "20px",
                opacity: "0.7"
              },
              alt: "Zen Tomato \xe2\x80\x93 A project by Travis Kaufman",
              height: "96",
              src: logo,
              width: "96"
            });
}

var $$default = LogoImage$default;

export {
  logo ,
  $$default ,
  $$default as default,
  
}
/* logo Not a pure module */
