// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as React from "react";

var nav = CssJs.style([
      CssJs.position(CssJs.absolute),
      CssJs.top(CssJs.px(20)),
      CssJs.left(CssJs.px(20)),
      CssJs.display("flex"),
      CssJs.flexDirection(CssJs.column),
      CssJs.media("(max-width: 600px)", [CssJs.flexDirection(CssJs.row)]),
      CssJs.alignItems(CssJs.center),
      CssJs.justifyContent(CssJs.center)
    ]);

var Styles = {
  nav: nav
};

function Nav$default(Props) {
  var children = Props.children;
  return React.createElement("nav", {
              className: nav
            }, children);
}

var $$default = Nav$default;

export {
  Styles ,
  $$default ,
  $$default as default,
  
}
/* nav Not a pure module */
