// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as React from "react";

var time = CssJs.style([
      CssJs.fontSize(CssJs.rem(12)),
      CssJs.media("(max-width: 720px)", [CssJs.fontSize(CssJs.rem(6))]),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 300
          }),
      CssJs.lineHeight({
            NAME: "abs",
            VAL: 1
          }),
      CssJs.letterSpacing(CssJs.rem(-0.015)),
      CssJs.margin2(CssJs.px(20), CssJs.auto)
    ]);

var Styles = {
  time: time
};

function TimeDisplay$default(Props) {
  var formattedSeconds = Props.formattedSeconds;
  return React.createElement("time", {
              className: time,
              dateTime: formattedSeconds
            }, formattedSeconds);
}

var $$default = TimeDisplay$default;

export {
  Styles ,
  $$default ,
  $$default as default,
  
}
/* time Not a pure module */
